[package]
name = "azul-box"
authors = ["Tahoso", "https://codeberg.org/Tahoso/azul-box"]
version = "0.1.78"
edition = "2024"
description = "A utility box for ffmpeg, yt-dlp, and more"
license = "GNU GENERAL PUBLIC LICENSE Version 3"
license-file = "LICENSE"
readme = "README.md"
homepage = "https://codeberg.org/Tahoso/azul-box"
repository = "https://codeberg.org/Tahoso/azul-box"

[package.metadata.deb]
assets = [
    [
        "target/release/azul-box",
        "/usr/bin/azulbox",
        "755",
    ],
    [
        "desktop/azul_box.desktop",
        "/usr/share/applications/azul_box.desktop",
        "644",
    ],
    [
        "assets/logo.png",
        "/usr/share/icons/azul_box.png",
        "644",
    ],
]

[dependencies]
dirs = "6.0.0"
eframe = "0.33.0"
image = "0.25.8"
lofty = "0.22.4"
native-dialog = "0.9.3"
notify-rust = "4.11.7"
rodio = "0.21.1"
scraper = "0.24.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
tokio = { version = "1.48.0", features = ["rt", "macros", "rt-multi-thread"] }
toml = "0.9.8"
ureq = { version = "3.1.4", features = ["json"] }
url = "2.5.7"
