name: Rust

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Linux and Windows Cross Compilers
        run: sudo apt-get install --yes --no-install-recommends libasound2-dev musl-tools gcc-mingw-w64-x86-64-win32

      - name: Install rustup targets
        run: rustup target add x86_64-unknown-linux-gnu x86_64-pc-windows-gnu

      - name: Build the executable
        run: cargo build --release --target x86_64-unknown-linux-gnu --target x86_64-pc-windows-gnu

      - name: output dir
        run: mkdir -p output

      - name: Tar x86_64 binary
        run: tar -czvf azul-box-x86_64-unknown-linux-gnu.tar.gz -C target/x86_64-unknown-linux-gnu/release azul-box

      - name: copy linux tag
        run: cp azul-box-x86_64-unknown-linux-gnu.tar.gz output/azul-box-x86_64-unknown-linux-gnu.tar.gz

      - name: Zip windows binary
        run: zip -j azul-box.exe-x86_64-pc-windows-gnu.zip target/x86_64-pc-windows-gnu/release/azul-box.exe

      - name: copy windows zip
        run: cp azul-box.exe-x86_64-pc-windows-gnu.zip output/azul-box.exe-x86_64-pc-windows-gnu.zip

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: binaries
          path: output/*
